// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eukenximajiuhrtljnpw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1a2VueGltYWppdWhydGxqbnB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5OTE0OTYsImV4cCI6MjA1ODU2NzQ5Nn0.P4U99VuGWgdPxJDsJ5LKnhvVQ1Rhgpwp9yqolRnuNJg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);